In [1]:
import numpy as np
import pandas as pd

In [2]:
# Carregando o conjunto de dados de teste e de treinamento com o pandas
train = pd.read_csv('datasets/titanic/train.csv')

test = pd.read_csv('datasets/titanic/test.csv')

In [3]:
# Os 4 primeiro dados do treinamento
train[:4]

PassengerId  Survived  Pclass   
0            1         0       3  \
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [4]:
# Analisando as colunas para ver se há alguns dados ausentes
# train.isnull().sum()
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
# Analisando as colunas para ver se há alguns dados ausentes
# test.isnull().sum()
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [6]:
# A mediana do conjunto de dados de treinamento será usada para preencher os nulos nas duas tabelas
impute_value = train['Age'].median()

train['Age'] = train['Age'].fillna(impute_value)

test['Age'] = test['Age'].fillna(impute_value)

In [7]:
# Adicionar uma coluna IsFemale como uma versão codificada da coluna 'Sex'
train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [8]:
# Algumas variáveis do modelo e criarei arrays NumPy
predictors = ['Pclass', 'IsFemale', 'Age']

# É melhor usar to_numpy() doque values
X_train = train[predictors].to_numpy()

X_test = test[predictors].to_numpy()

y_train = train['Survived'].to_numpy()

X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [9]:
# Mostrando os 5 primeiro de y_train
y_train[:5]

array([0, 1, 1, 1, 0])

In [10]:
# Usando o modelo LogisticRegression do scikit-learn e criando uma instância do modelo
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [11]:
# Adequação do modelo aos dados de treinamento utilizando o método fit do modelo
model.fit(X_train, y_train)

LogisticRegression()

In [12]:
# Fazer previsões para o conjunto de dados de teste usando model.predict
y_predict = model.predict(X_test)
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [13]:
# Se tivesse os valores verdadeiros para o conjunto de dados de teste, poderia calcular uma métrica, 
# como percentual de exatidão

#(y_true == y_predict).mean()

In [14]:
# Validação cruzada e parâmetro C de regularização do modelo
from sklearn.linear_model import LogisticRegressionCV

model_cv = LogisticRegressionCV(Cs=10)

model_cv.fit(X_train, y_train)

LogisticRegressionCV()

In [15]:
# cross_val_score para para cuidar do processo de separação dos dados
from sklearn.model_selection import cross_val_score

model = LogisticRegression(C=10)

scores = cross_val_score(model, X_train, y_train, cv=4)

scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])